name: Run Dooin Crawler Once

on:
  workflow_dispatch:  # 수동 실행 허용

permissions:
  contents: write

jobs:
  run-dooin-crawler:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 체크아웃
        uses: actions/checkout@v3

      - name: Python 설정
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: 필수 패키지 설치
        run: |
          pip install -r requirements.txt

      - name: 크롤러 실행
        run: |
          python dooin.py

      - name: 결과 파일 커밋 & 푸시
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "dooin-bot"
          git add data/dooin_result.xlsx
          git commit -m "크롤링 자동 실행 결과" || echo "No changes"
          git push
